version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    working_dir: /var/www/laravel
    volumes:
      - ./:/var/www
      - ./public:/var/www/public
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - laravel

networks:
  laravel:

volumes:
  postgres_data: